# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rob King
email: robbyking3@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "works with computers."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.robking.co" # the base hostname & protocol for your site
twitter_username: wscreative
codepen_username: robbyking3
github_username:  robbyking3


permalink:     /work/:title.html
# Build settings
markdown: kramdown

gems:
  - octopress-autoprefixer